apiVersion: v1
kind: Service
metadata:
  name: airflow-web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-flower
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
      nodePort: 32081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: i05nagai/kubernetes-airflow
        imagePullPolicy: IfNotPresent
        env:
        - name: AIRFLOW_HOME
          value: ${AIRFLOW_HOME}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        - name: REDIS_PASSWORD
          value: ${REDIS_PASSWORD}
        ports:
        - name: web
          containerPort: 8080
        args: ["webserver"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-flower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: i05nagai/kubernetes-airflow
        imagePullPolicy: IfNotPresent
        env:
        - name: AIRFLOW_HOME
          value: ${AIRFLOW_HOME}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        - name: REDIS_PASSWORD
          value: ${REDIS_PASSWORD}
        ports:
        - name: flower
          containerPort: 5555
        args: ["flower"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      restartPolicy: Always
      containers:
      - name: scheduler
        image: i05nagai/kubernetes-airflow
        imagePullPolicy: IfNotPresent
        env:
        - name: AIRFLOW_HOME
          value: ${AIRFLOW_HOME}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        - name: REDIS_PASSWORD
          value: ${REDIS_PASSWORD}
        args: ["scheduler"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      restartPolicy: Always
      containers:
      - name: worker
        image: i05nagai/kubernetes-airflow
        imagePullPolicy: IfNotPresent
        env:
        - name: AIRFLOW_HOME
          value: ${AIRFLOW_HOME}
        # if you are root user
        - name: C_FORCE_ROOT
          value: "true"
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        - name: REDIS_PASSWORD
          value: ${REDIS_PASSWORD}
        args: ["worker"]
