apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: redis
  ports:
    - name: node
      protocol: TCP
      port: 6379
      targetPort: node
    - name: management
      protocol: TCP
      port: 16379
      targetPort: management
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: db
    spec:
      containers:
      - name: mysql
        image: "mysql:8.0.3"
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "airflow"
        - name: MYSQL_DATABASE
          value: "airflow"
        - name: MYSQL_USER
          value: "airflow"
        - name: MYSQL_PASSWORD
          value: "airflow"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: redis
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: redis
        ports:
        - name: management
          containerPort: 16379
        - name: node
          containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: "airflow"
