apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  type: NodePort
  selector:
    app: docker
  ports:
    - name: docker
      protocol: TCP
      port: 2375
      targetPort: docker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker
    spec:
      restartPolicy: Always
      containers:
      - name: docker
        image: "i05nagai/docker:latest"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: "docker"
          mountPath: "/var/lib/docker.sock"
        ports:
        - name: web
          containerPort: 2375
      volumes:
        - name: "docker"
          hostPath:
            path: "/var/lib/docker.sock"
