apiVersion: v1
kind: Service
metadata:
  name: mysql-sample
spec:
  type: ClusterIP
  selector:
    app: mysql-sample
  ports:
    - name: mysql-sample
      protocol: TCP
      port: 3307
      targetPort: mysql-sample
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-sample
    spec:
      containers:
      - name: mysql-sample
        image: i05nagai/mysql-sample:latest
        ports:
        - name: mysql-sample
          containerPort: 3307
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
