apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-airflow-environment-variable
data:
  # AWS
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  # docker
  DOCKER_REGISTRY_HOST: ${DOCKER_REGISTRY_HOST}
  DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE}
  DOCKER_REGISTRY_HOST: ${DOCKER_REGISTRY_HOST}
  DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE}
  WORKFLOW_AIRFLOW_USERNAME: ${WORKFLOW_AIRFLOW_USERNAME}
  WORKFLOW_AIRFLOW_EMAIL: ${WORKFLOW_AIRFLOW_EMAIL}
  # GCP
  GOOGLE_APPLICATION_CREDENTIALS: '${GCP_IAM_JSON_KEY_PATH}'
  DOCKER_URL: ${DOCKER_URL}
  ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
  GCP_PROJECT_ID: ${GCP_PROJECT_ID}
  GCP_BIG_QUERY_DATASET: ${GCP_BIG_QUERY_DATASET}
  GCP_IAM_JSON_KEY_PATH: '${GCP_IAM_JSON_KEY_PATH}'
  SLACK_WEBHOOK_URL: '${SLACK_WEBHOOK_URL}'
