---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: home-nfs-server
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-nfs-server
  template:
    metadata:
      labels:
        app: home-nfs-server
    spec:
      containers:
      - name: home-nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /srv/volume/shared/home
            name: home
      volumes:
        - name: home
          gcePersistentDisk:
            pdName: home
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: home-nfs-server
  namespace: home
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: home-nfs-server
