apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-initdb
spec:
  template:
    metadata:
      name: airflow-initdb
    spec:
      containers:
        - image: ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE_BASE}/workflow-airflow:latest
          imagePullPolicy: ${DOCKER_IMAGE_PULL_POLICY}
          command: ["airflow", "initdb"]
          name: airflow-initdb
          env:
            # required if you run as root
          - name: C_FORCE_ROOT
            value: "true"
          envFrom:
          - configMapRef:
              name: airflow-environment-variable
          - secretRef:
              name: airflow-environment-variable
          - configMapRef:
              name: mysql-environment-variable
          - secretRef:
              name: mysql-environment-variable
      restartPolicy: OnFailure
      nodeSelector:
        cloud.google.com/gke-nodepool: core-node-pool-lpc
