---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv-nfs
  namespace: home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "home-nfs-server.home.svc.cluster.local"
    path: "/"
