---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pvc-nfs-home
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
