#!/bin/bash

set -e
if [[ -z ${PATH_TO_CONFIG_DIR+x} ]]; then
  readonly PATH_TO_CONFIG_DIR=$(cd $(dirname ${0})/../config;pwd)
fi

source ${PATH_TO_CONFIG_DIR}/secret/env.sh
source ${PATH_TO_CONFIG_DIR}/var/env.sh


export ENVIRONMENT_NAME
export GCP_BIG_QUERY_DATASET
export SLACK_WEBHOOK_URL
export DOCKER_REGISTRY_HOST
export DOCKER_IMAGE_BASE
export AWS_IAM_ACCESS_KEY_ID
export AWS_IAM_SECRET_KEY
export AWS_DEFAULT_REGION
export AWS_RDS_PASSWORD
export DOCKER_URL
export DOCKER_HOST
export GCP_PROJECT_ID
export GCP_IAM_JSON_KEY_DATA
export GCP_IAM_JSON_KEY_PATH
export SLACK_WEBHOOK_URL
# datadog
export DATADOG_API_KEY
# airflow
export WORKFLOW_AIRFLOW_USERNAME
export WORKFLOW_AIRFLOW_PASSWORD
export WORKFLOW_AIRFLOW_EMAIL
# REDIS
export WORKFLOW_REDIS_PASSWORD
# MYSQL
export WORKFLOW_MYSQL_DATABASE
export WORKFLOW_MYSQL_PASSWORD
export WORKFLOW_MYSQL_ROOT_PASSWORD
export WORKFLOW_MYSQL_USER
